name: Deploy VitePress site to Pages

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create and Push Tag
        if: ${{ github.event.pull_request.merged == true && github.ref_name == 'main' }}
        id: create_tag
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"

          # 正規表現でvX.X.X形式のバージョンを抽出
          VERSION=$(echo $PR_TITLE | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')

          # バージョンが見つからなかった場合はエラーを返す
          if [ -z "$VERSION" ]; then
            echo "エラー: PRタイトルにvX.X.X形式のバージョンが見つかりません" >&2
            exit 1
          fi

          echo "NEW_TAG=$VERSION" >> $GITHUB_ENV

      - name: Create Release Tag
        if: ${{ github.event.pull_request.merged == true && github.ref_name == 'main' }}
        run: |
          gh release create ${{env.NEW_TAG}} --generate-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    needs: create-release-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: yarn
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build with VitePress
        run: yarn run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist
      - name: build pdf
        if: ${{ github.event.pull_request.merged == true && github.ref_name == 'main' }}
        run: yarn run build:pdf
      - name: Upload PDF artifact
        if: ${{ github.event.pull_request.merged == true && github.ref_name == 'main' }}
        run: |
          gh release upload ${{needs.create-release-tag.outputs.new_tag}} ./output/resume.pdf --clobber
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
